### ISSUE TITLE
Needs to be paired each time

### ISSUE THREAD

**Issue by undeadindustries** [MiSTer-devel/xow_MiSTer#5]
I just downloaded and set this up today. It works great other than every time I turn off and on the Mister, it needs to be re-paired.

Thanks!

**Comment by sorgelig** [comment]
cannot confirm.
Works fine for me after power-cycling of MiSTer. Controller connects without re-pairing.

**Comment by sofakng** [comment]
> I just downloaded and set this up today. It works great other than every time I turn off and on the Mister, it needs to be re-paired.
> 
> Thanks!

Have you updated the controller firmware to the latest version?

**Comment by undeadindustries** [comment]
I have not. I'll try that tonight. Thanks!

**Comment by undeadindustries** [comment]
I just tried that and it worked. thank you!
