### ISSUE TITLE
Turbografx16 - CD core freezing not loading the games with XOV loaded

### ISSUE THREAD

**Issue by gamingarena23** [MiSTer-devel/xow_MiSTer#6]
with any new version of Linux after v210711 you have to disable XOV to be able to load Turbografx16 - CD other wise will freeze on bios screen or just get stuck with " please wait..."  If you connect Xbox One controller wired and unload the XOV driver everything is back to normal all CD games load as they should.

**Comment by tcamargo** [comment]
Problem only happens with TGFX16-CD games. Other cores, even MegaCD, work without problem with xow.
Using my xbox pad in BT mode for the time being.

**Comment by tcamargo** [comment]
Solved in https://misterfpga.org/viewtopic.php?t=147&p=33709#p33709.

**Comment by sorgelig** [comment]
ah, i've forgot completely about xow!
Yes, i've added xow in latest Linux, so you don't need any scripts

**Comment by tcamargo** [comment]
Just noticed xow is in /sbin and autoloads when necessary. Nice update! 

> ah, i've forgot completely about xow!
> Yes, i've added xow in latest Linux, so you don't need any scripts
